## 通过 Numpy 创建各式各样的矩阵

参考：http://blog.51cto.com/qianqiansun/1964097

In [15]:
import numpy as np

## 二、用指定的数据填充

### 1. array(object[, dtype, copy, order, subok, ndmin])

* 用对象直接填充数组
* object 中括号括起来的数组
* ndmin 表示维度

In [16]:
np.array([1, 2, 3])    # 一维数组

array([1, 2, 3])

In [17]:
np.array([[1, 2], [3, 4]])    # 二维数组

array([[1, 2],
       [3, 4]])

In [18]:
np.array([1, 2, 3], ndmin=2)    # 只有一个元素的二维数组

array([[1, 2, 3]])

In [19]:
np.array(np.mat('1 2; 3 4'))    # 从子类（矩阵）创建

array([[1, 2],
       [3, 4]])

### 2. numpy.mat(data,dtype=None) 

* 输入转化为矩阵,创建一个新变量,指向旧的数据
* numpy中数组和矩阵的区别 - jiangsujiangjiang的博客 - CSDN博客  https://blog.csdn.net/jiangsujiangjiang/article/details/83714475
* matrix是array的分支，matrix和array在很多时候都是通用的，用哪一个都一样；
* 如果两个可以通用，那就选择array，因为array更灵活，速度更快，很多人把二维的array也翻译成矩阵。
* 相同点：索引方式相同，都可以使用a[i][j]，a[i,j]进行索引
* numpy.mat(), numpy.array() 可以保证两者的互相转换

matrix（矩阵）：

* 具有相对简单的运算符号，比如两个matrix相乘（求内积），就是用符号*

array（数组）：
* 两个一维数组相乘用\*，对应元素相乘
* 多维数组也可以看成矩阵，如果进行矩阵相乘（求内积），则需要用到np.dot(），如np.dot(arr.T,arr)

In [20]:
np.mat('1 2; 3 4')    # 矩阵

matrix([[1, 2],
        [3, 4]])

In [21]:
a = np.mat('1 2 3 4')    # 一维矩阵
a

matrix([[1, 2, 3, 4]])

In [22]:
b = a.T
b

matrix([[1],
        [2],
        [3],
        [4]])

In [23]:
a*b

matrix([[30]])

In [24]:
b*a

matrix([[ 1,  2,  3,  4],
        [ 2,  4,  6,  8],
        [ 3,  6,  9, 12],
        [ 4,  8, 12, 16]])

### 3. asarray(a[, dtype, order])

* 把lists, lists of tuples, tuples, tuples of tuples, tuples of lists and ndarrays转化为array

In [25]:
a = [1, 2, 3]
np.asarray(a)

array([1, 2, 3])