## 通过 Numpy 创建各式各样的矩阵

参考：http://blog.51cto.com/qianqiansun/1964097

In [34]:
import numpy as np

## 一、使用系统方法

### 1. arange([start,] stop[, step,][, dtype])

* 根据给定的区间创建连续的值
* start 为开始的数值，3 对应 int，3.0 对应 float
* stop 为结束的数值
* step 为步长
* dtype 为格式

In [35]:
np.arange(5)    # 从0开始，不包括stop值

array([0, 1, 2, 3, 4])

In [36]:
np.arange(5.0)    # float

array([0., 1., 2., 3., 4.])

In [37]:
np.arange(3, 8)    # with start value, but without stop value

array([3, 4, 5, 6, 7])

In [38]:
np.arange(1, 15, 3)    # with a specific step

array([ 1,  4,  7, 10, 13])

### 2. ones(shape[, dtype, order])   

* 生成一个指定shape和dtype的数组，用1填充
* shape 可以通过 (2, 3) 样式来输入，此为 2 行 3 列 的矩阵
* dtype 可以限定数据类型，例如：dtype=int
    


In [39]:
np.ones((2, 3))    # 二维

array([[1., 1., 1.],
       [1., 1., 1.]])

In [40]:
np.ones((2, 3), dtype=int)    # 二维整数

array([[1, 1, 1],
       [1, 1, 1]])

In [41]:
np.ones(5)   # 一维，默认格式

array([1., 1., 1., 1., 1.])

### 3. ones_like(a[, dtype, order, subok])

* 和ones的区别就是需要给定一个dnarray模板，新生成的array继承了a的shape和dtype

In [42]:
x = np.arange(6)
x = x.reshape(2, 3)
x

array([[0, 1, 2],
       [3, 4, 5]])

In [43]:
np.ones_like(x)

array([[1, 1, 1],
       [1, 1, 1]])

### 4. zeros(shape[, dtype, order])   

* 根据给定的shape，和dtype生成一个由0填充的数组
* 与上面的 ones 性质类似

In [44]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [45]:
np.zeros(8)

array([0., 0., 0., 0., 0., 0., 0., 0.])

### 5. zeros_like(a[, dtype, order, subok])

* 和zeros的区别就是需要给定一个dnarray模板，新生成的array继承了a的shape和dtype

In [46]:
z = np.arange(9).reshape(3,3)
z

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [47]:
np.zeros_like(z)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

### 6. full(shape, fill_value[, dtype, order])

* 用指定的值填充数组

In [48]:
np.full((3, 3), 5)

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

### 7. full_like(a, fill_value[, dtype, order, subok])

* 根据a模板的shape和dtype生成一个数组，如果指定的填充数不是a的dtype类型，会向下取整，这时候也可以指定新数组的dtype类型。

In [49]:
x = np.arange(6, dtype=np.int)
np.full_like(x, 1)

array([1, 1, 1, 1, 1, 1])

In [50]:
np.full_like(x, 1.2)    # 取整

array([1, 1, 1, 1, 1, 1])

In [51]:
np.full_like(x, 2.8)

array([2, 2, 2, 2, 2, 2])

In [52]:
np.full_like(x, 1.2, dtype=np.float)

array([1.2, 1.2, 1.2, 1.2, 1.2, 1.2])

In [53]:
np.full_like(x, np.nan, dtype=np.double)

array([nan, nan, nan, nan, nan, nan])

### 8. empty(shape[, dtype, order])

* 根据给定的参数创建一个ndarray数组，值用随机数填充

In [54]:
np.empty((2, 2))

array([[1., 2.],
       [3., 4.]])

In [55]:
np.empty([2, 2])

array([[1., 2.],
       [3., 4.]])

### 9. empty_like(a[, dtype, order, subok]) 

* 和empty不同的是，需要给出一个array的模板，就是a参数，新生成的ndarray继承了a的shape和dtype

In [56]:
a = ([1,2,3],[4,5,6])
a

([1, 2, 3], [4, 5, 6])

In [57]:
np.empty_like(a)

array([[-1652807184,         431,           0],
       [          0,           1,         116]])

### 10. eye(N[, M, k, dtype]) 

* 生成一个N行M列的数组，K指定一条斜线，这条斜线上的值都是1,数组的其他元素维0

In [58]:
np.eye(5, 5, 1)

array([[0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.]])

In [59]:
np.eye(5, 5, 3)

array([[0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

### 11. identity(n[, dtype])

* 生成一个正方形的数组即N×N类型的数组，且索引万恶哦0的斜线上维1,其他元素维0

In [60]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])